### ISSUE TITLE
Circuit Diagram

### ISSUE THREAD

**Issue by BojeThomas** [bitluni/ESP32-S3-VGA#1]
Great Idea,
but will you also provide circuit diagram from your adapter in the video or all files to generate this or provide an link to order it?

**Comment by BrainBoardz** [comment]
This ESP32S3 VGA project from Bitluni is an amazing leap forward! It's a considerable effort for sure. and greatly appreciated. 
I do  understand that the current codebase is very much a work in progress, but it would be great if, in the meantime, we could get access to the schematic as BojeThomas has requested. There's a hint of the schematic in the videos, but more details on the components of the resistor ladder etc. would be very welcome. I can't wait to see what hardware and software is going to be created based on this library. Sign me up if you release some boards!

 I'm wondering if there is a gaming library that could be made to work with this (similar to NCAT perhaps).  VGA level gaming on an ESP32S3 would be so cool! So much potential here!

**Comment by bitluni** [comment]
Circuit is shown in the official documentation of the board, the qr-code on the packaging also leads there :-)
https://bitluni.net/vga-s3
